"""init migrate

Revision ID: 14c547278e19
Revises: 
Create Date: 2024-06-20 17:53:55.182145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c547278e19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celestial_bodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('spacecrafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('fuel_log', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('launch_date', sa.DateTime(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('spacecraft_id', sa.Integer(), nullable=False),
    sa.Column('celestial_body_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celestial_body_id'], ['celestial_bodies.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['spacecraft_id'], ['spacecrafts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missions')
    op.drop_table('spacecrafts')
    op.drop_table('players')
    op.drop_table('celestial_bodies')
    # ### end Alembic commands ###
